spring.application.name=hotel-engelnieves

# Puerto dinámico (Railway lo inyecta)
server.port=${PORT:8080}

# Conexión a Base de Datos
spring.datasource.url=jdbc:${DATABASE_URL:mysql://localhost:3306/hotel_db}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# DevTools
spring.devtools.restart.enabled=true
